### ISSUE TITLE
rx.exceptions.OnErrorNotImplementedException: Download Failed

### ISSUE THREAD

**Issue by potny** [esafirm/RxDownloader#1]
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.example.app (has extras) } in com.example.app.data.remote.RxDownloader$DownloadStatusReceiver@424d99f0
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:778)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5057)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: rx.exceptions.OnErrorNotImplementedException: Download Failed
    at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
    at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
    at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
    at rx.subjects.PublishSubject$PublishSubjectProducer.onError(PublishSubject.java:316)
    at rx.subjects.PublishSubject$PublishSubjectState.onError(PublishSubject.java:231)
    at rx.subjects.PublishSubject.onError(PublishSubject.java:78)
    at com.example.app.data.remote.RxDownloader$DownloadStatusReceiver.onReceive(Unknown Source)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
    ... 9 more
Caused by: java.lang.IllegalStateException: Download Failed
    ... 11 more
```

**Comment by esafirm** [comment]
The stack trace is self explanatory, you have to implement `onError`

Will provide `README` soon. Thanks! 😄
